### ISSUE TITLE
Ores missing

### ISSUE THREAD

**Issue by BasisBeer** [ObliviousSpartan/SpartanWeaponry-API#60] opened 2024-07-22 07:03 UTC
for some reason, the item tag of every ore is missing. The item just doesnt exist. I use spartan weaponry in version 1.20.1 in forge 47.3.0. Do i need to add another mod to fix this? 
![image](https://github.com/user-attachments/assets/95e913ad-a135-4902-92f1-aae88ba0359d)

**Comment by Mindriddle09** [comment] 2024-07-23 18:33
Im having the SAME problem lol. I found many different one with all the ores i need but its for older versions, all of them and its making me annoyed. I hope someone helps.

**Comment by Palkia1995** [comment] 2024-07-24 17:43
Hey :D
i can help

you can use the mod "evolved resources" they are compatible with spartan i have these mods in my minecraft instance and was testing it today and all things are craft able from spartan, but one thing if you would like to craft items like invar, steel etc. you need to make your own recipes (crafttweaker, kubejs), if not may i suggest using the mods thermal series (thermal foundation,expansion etc) 

i hope this can be helpful

**Comment by ObliviousSpartan** [comment] 2024-07-30 13:56
Hey,
Ores being missing is by design, since a *lot* of mods add their own ores and I didn't want to add the umpteenth variant of Tin Ore, Lead Ore, etc. This design was derived from how I developed Spartan Shields too.
As @Palkia1995 has said, Evolved Resources works with this mod and in issue #62 suggested the mod All the Ores (ATO), which also works.
I just checked out Thermal Foundation for 1.20.1 and while it does add most materials for the weapons, it also doesn't have materials for Steel, Platinum and Aluminum.
Closing this issue

**Closed as not planned by ObliviousSpartan** 2024-07-30 13:56 UTC
Labels: question, wontfix, 1.20.1
