### ISSUE TITLE
forge ingots

### ISSUE THREAD

**Issue by gittyboy30** [ObliviousSpartan/SpartanWeaponry-API#28] opened 2024-03-09 22:11 UTC
so, there's a problem with the ores where when you hover over some/most of the weapons same with the Spartan shields any answers.  

![Screenshot (17)](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/162842094/551c0249-4fa7-4fe8-a94d-493f66277278)
![Screenshot (18)](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/162842094/7f921e51-28e8-4155-a136-46983bd6f53b)

**Comment by alexvirgo13** [comment] 2024-03-17 13:14
Those are modded materials and that text means that there's no mod adding the corresponding ingot, try to instal a mod with those(immersive engineering for example) to see if the text dissapears

**Comment by ObliviousSpartan** [comment] 2024-03-17 15:14
Yeah basically this. This mod doesn't provide any ingots to make said weapons. It just adds compatibility with pre-existing ingots from other mods. 
You'll need to install a separate mod (or mods) that add these ingots for this message to disappear.
There is also a config option that allows you to hide any weapon with invalid recipes if you don't want to see this message. You can find it in the "spartanweaponry-common.toml" file in the config folder of your mod instance. Look for the value "force_show_disabled_items" under the "jei" category.
Closing this issue as this is intended behavior.

**Closed as completed by ObliviousSpartan** 2024-03-17 15:14 UTC
Labels: wontfix
