### ISSUE TITLE
What mods are needed for the Compatible Ores

### ISSUE THREAD

**Issue by Mindriddle09** [ObliviousSpartan/SpartanWeaponry-API#62] opened 2024-07-23 18:29 UTC
I also have the JEI mod and i see that there are a lot more weapons in materials i havent had before and iv'e been looking for mods to see which ojnes i can use but cant seem to find any. Is there any specific mod/mods I am supposed to have because i've been at this for a solid 30 minutes and can't figure it out. I looked through the comments on curseforge, searched many things relating to ores, and more and still nothing. So right now im very confused. PLS HELP 😭😭!! Btw im on Version 1.19.2

**Comment by Palkia1995** [comment] 2024-07-24 18:15
hey 
so i have tested it today with minecraft 1.19.2 the mod ATO and spartan weaponry, ATO=alltheores, i think its the best mod that i found that is adding ores in 1.19.2 and yes it is compatible, i can craft for example the silver longsword or the bronze dagger etc 
i hope this can help :D

**Comment by ObliviousSpartan** [comment] 2024-07-30 13:59
Hey,
Ores being missing is by design, since a lot of mods add their own ores and I didn't want to add the umpteenth variant of Tin Ore, Lead Ore, etc. This design was derived from how I developed Spartan Shields too.
As @Palkia1995 has said, All the Ores (ATO) works with this mod and in issue #60, Evolved Resources also works.
I just checked out Thermal Foundation for 1.20.1 and while it does add most materials for the weapons, it also doesn't have materials for Steel, Platinum and Aluminum.
Closing this issue

**Closed as not planned by ObliviousSpartan** 2024-07-30 13:59 UTC
Labels: question, wontfix, 1.19.2
