### ISSUE TITLE
throwing boomerangs adds a new one to inventory after every throw

### ISSUE THREAD

**Issue by snipeshot104** [ObliviousSpartan/SpartanWeaponry-API#14] opened 2024-01-01 16:28 UTC
while play testing the new 1.18 update i noticed that i kept getting more diamond boomerangs in my inventory after every throw. im not sure if anyone else is having this problem but the only mods im playing with are target dummy, spartan weaponry and spartan shields

**Comment by 821lemur** [comment] 2024-01-01 19:11
I have the same problem with all boomerangs

**Comment by ObliviousSpartan** [comment] 2024-01-03 15:04
Wow that was quite an oversight! This was caused by the catching code being called twice when the Boomerang returns to the thrower. It doesn't seem to affect other throwing weapons though. 
I'll release a fix for this soon.

**Comment by 821lemur** [comment] 2024-01-04 20:22
Harika, teşekkürler!

ObliviousSpartan ***@***.***>, 3 Oca 2024 Çar, 18:05
tarihinde şunu yazdı:

**Comment by ghost** [comment] 2024-01-06 10:50
Single player games have this issue, but it is not present on the server.

**Comment by ObliviousSpartan** [comment] 2024-01-06 13:04
Just uploaded the fix with the new version "3.0.2 beta 3" on both Curseforge and Modrinth.
Closing the issue as fixed; reopen it if the issue persists.

**Closed as completed by ObliviousSpartan** 2024-01-06 13:04 UTC
Labels: bug, 1.18.2
