### ISSUE TITLE
Problem with Shoulder Surfing and throwing weapons (1.19.2)

### ISSUE THREAD

**Issue by YuriFernandes150** [ObliviousSpartan/SpartanWeaponry-API#35] opened 2024-05-02 01:02 UTC
There seems to be a problem when you use a throwing weapon (tomahawks, throwing knifes, etc) and using [Shoulder Surfing Reloaded](https://www.curseforge.com/minecraft/mc-mods/shoulder-surfing-reloaded).

[Crash Report](https://bytebin.lucko.me/5l39p9UABp)
![image](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/16628285/b5b62d58-3c64-4b7a-8608-3f608d17eeff)

Players with the shoulder surfing mod installed cant even log into the server if they have a throwing weapon equipped, I have to always edit it out of their inventories with NBTExplorer.

I've done some reading on [this issue](https://github.com/ObliviousSpartan/SpartanWeaponry/issues/21) already, but was unable to make it work.
I tried to not use the new crosshair, as stated in the previous issue that the crosshair was causing the problem, but still with no success:
![image](https://github.com/ObliviousSpartan/SpartanWeaponry/assets/16628285/c9490c7d-53e5-46a9-b240-c26f4299ff1d)

**Comment by Gabrielzin0** [comment] 2024-05-08 17:03
i got the same error, i tried absolutely everything i could, and by the looks of it, is every weapon that has "ammo" that you can throw like knifes, javelins.. i think the devs will need to update for them to work together!

**Comment by ObliviousSpartan** [comment] 2024-05-09 14:33
Hey,
Yeah the issue is due to an update to Shoulder Surfing Reloaded that changed where certain parts of code are located.
In the meantime, you might need to roll back the version of Shoulder Surfing Reloaded to the version supported. I think I was using version 2.9.7 (the one before version 3.0.0).
I checked the changelog for version 3.0.0 and yeah... it does mention 3rd party plugins breaking.
Also, I figured out this also affects the 1.18.2 version as well.
This will be fixed in the next update.

**Comment by Gabrielzin0** [comment] 2024-05-14 04:52
> Hey, Yeah the issue is due to an update to Shoulder Surfing Reloaded that changed where certain parts of code are located. In the meantime, you might need to roll back the version of Shoulder Surfing Reloaded to the version supported. I think I was using version 2.9.7 (the one before version 3.0.0). I checked the changelog for version 3.0.0 and yeah... it does mention 3rd party plugins breaking. Also, I figured out this also affects the 1.18.2 version as well. This will be fixed in the next update.

thanks for the info!

**Comment by ObliviousSpartan** [comment] 2024-06-12 12:39
I've uploaded a fix for this issue that should go live soon. Hopefully this is the last time Shoulder Surfing Reloaded causes a crash with this one lol
Closing issue

**Comment by ObliviousSpartan** [comment] 2024-06-12 15:27
Oh no... I opened my big mouth... I tested this fix with version 4.0+ of Shoulder Surfing Reloaded and guess what? It crashed... AGAIN... and I'm gonna have to fix it... yet again

**Comment by ObliviousSpartan** [comment] 2024-06-14 16:06
Fixed it again in the new 1.19.2 and the 1.20.1 versions. Yeah that's out now.
Closing issue

**Closed as completed by ObliviousSpartan** 2024-06-14 16:06 UTC
Labels: crash, 1.18.2, cross-mod incompatibility, 1.19.2
